name: Release

on:
  push:
    tags: ['v*']

jobs:
  build-basic:
    name: Build without any extra features
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      #- name: Configure cache
      #  uses: Swatinem/rust-cache@v2

      - name: Build release binary
        run: cargo build --release --no-default-features

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: basic-release-binary
          path: target/x86_64-pc-windows-msvc/release/click-once.exe

  build-logging:
    name: Build with logging feature
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      #- name: Configure cache
      #  uses: Swatinem/rust-cache@v2

      - name: Build release binary
        run: cargo build --release --no-default-features --features=logging

      - name: Rename file
        run: mv target/x86_64-pc-windows-msvc/release/click-once.exe click-once-logging.exe

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: logging-release-binary
          path: click-once-logging.exe

  build-tray:
    name: Build with tray feature
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      #- name: Configure cache
      #  uses: Swatinem/rust-cache@v2

      - name: Build release binary
        run: cargo build --release --no-default-features --features=tray,logging

      - name: Rename file
        run: mv target/x86_64-pc-windows-msvc/release/click-once.exe click-once-tray.exe

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: tray-release-binary
          path: click-once-tray.exe

  build-small-tray:
    name: Build with tray feature and Nightly optimizations
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: "rust-src"

      #- name: Configure cache
      #  uses: Swatinem/rust-cache@v2

      - name: Build release binary
        env:
          RUSTFLAGS: "-Zlocation-detail=none -Zfmt-debug=none"
        run: cargo +nightly build --release --no-default-features --features=tray,logging -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort,optimize_for_size

      - name: Rename file
        run: mv target/x86_64-pc-windows-msvc/release/click-once.exe click-once-tray-small.exe

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: tray-small-release-binary
          path: click-once-tray-small.exe

  release:
    name: Release
    runs-on: windows-latest
    needs: [build-basic, build-logging, build-tray, build-small-tray]
    permissions:
      contents: write
    steps:
      - name: Download basic binary from previous job
        uses: actions/download-artifact@v4
        with:
          name: basic-release-binary

      - name: Download logging binary from previous job
        uses: actions/download-artifact@v4
        with:
          name: logging-release-binary

      - name: Download tray binary from previous job
        uses: actions/download-artifact@v4
        with:
          name: tray-release-binary

      - name: Download small tray binary from previous job
        uses: actions/download-artifact@v4
        with:
          name: tray-small-release-binary

      # Create the release:  https://github.com/actions/create-release
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{github.ref}}
          release_name: click-once ${{ github.ref }}
          draft: false
          prerelease: false

      # Upload release assets:   https://github.com/actions/upload-release-asset
      - name: Upload release asset
        id: upload-basic
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: click-once.exe
          asset_name: click-once.exe
          # https://stackoverflow.com/questions/41459168/which-mime-type-is-correct-for-the-exe-file
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload release asset
        id: upload-logging
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: click-once-logging.exe
          asset_name: click-once-logging.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload release asset
        id: upload-tray
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: click-once-tray.exe
          asset_name: click-once-tray.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload release asset
        id: upload-tray-small
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: click-once-tray-small.exe
          asset_name: click-once-tray-small.exe
          asset_content_type: application/vnd.microsoft.portable-executable